# Generated by Django 5.2.4 on 2025-08-12 13:02

import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_photo_flight_photo_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photos.models.photo_upload_name),
        ),
        migrations.AlterField(
            model_name='photo',
            name='meta_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='meta_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
