# Generated by Django 5.2.4 on 2025-08-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_datetime_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
