# Generated by Django 5.2.4 on 2025-08-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='name',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='user',
        ),
        migrations.AddField(
            model_name='flight',
            name='flightradar_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='operating_airline',
            field=models.CharField(blank=True, null=True),
        ),
    ]
